version: '3.8'

volumes:
  postgres:

services:
  postgres:
    container_name: demo_postgres
    labels:
      org.springframework.boot.service-connection: postgres
    image: "postgres:15"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped